### ISSUE TITLE
Add associations

### ISSUE THREAD

**Issue by nidalaa** [cool-beetles/web_treasures#9]
Please add associations to created models according to the schema:

<img width="1111" alt="screen shot 2017-11-09 at 22 06 07" src="https://user-images.githubusercontent.com/7466903/32629666-4373c3f0-c59a-11e7-9cd7-e47ac0f45e3e.png">

Please test all defined associations in Rails console by creating and retrieving objects through associations (and copy console output into comment in this issue).

**Comment by cool-beetles** [comment]
![rails_c](https://user-images.githubusercontent.com/26188232/33336347-e9f561dc-d46f-11e7-8baa-279277fccaf4.png)
